server:
  port: 8090
  use-forward-headers: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.blog/db/blog
    username: admin
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/Blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  freemarker:
    settings:
      number_format: 0.##


